title: IEEE Smart World Congress 2026
email: rmorland@athabascau.ca
description: >- # this means to ignore newlines until "baseurl:"
  Join us for the 2026 IEEE Smart World Congress in Cosenza, Calabria, Italy August 2026
baseurl: "/"
url: "https://ieee-swc-2026.github.io"
author:
  name: "IEEE SWC 2026 Organizing Committee"
  email: "rmorland@athabascau.ca"
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
